[package]
name = "ndc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ndc_lib"
path = "src/lib.rs"

[profile.release]
strip = true
lto = true

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
num = "0.4.1"
rustyline = {  version = "13.0.0", optional = true, features = ["derive"] }
ryu = "1.0.17"
thiserror = "1.0.58"

[features]
default = ["repl"]
repl = ["dep:rustyline"]
