[package]
name = "ndc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
rustyline = {  version = "13.0.0", optional = true, features = ["derive"] }

[features]
default = ["repl"]
repl = ["dep:rustyline"]